### ISSUE TITLE
ES 5 installation

### ISSUE THREAD

**Issue by mingruimingrui** [alexklibisz/approximate-vector-search#8]
Hi would there be ports for ES5 in the future?

**Comment by alexklibisz** [comment]
Like elasticsearch 5?
Probably not.
I'm currently not really working on this project anymore.
If you feel comfortable, it shouldn't be too hard to copy/paste the Java code and modify any ES API calls that changed.

**Comment by mingruimingrui** [comment]
That's cool! I'm going to make a fork of your repo.
~~Mind teaching me how to use the benchmarking tools you made and some expected figures?~~
I'm going to refer to https://github.com/alexklibisz/elastik-nearest-neighbors/blob/master/elasticsearch-aknn/benchmark/README.md

**Comment by mingruimingrui** [comment]
Quick question,  what is k1 and k2? I don't quite understand what this hyper parameter represent

**Comment by mingruimingrui** [comment]
Btw, my build for 5.6.5 is successful!
https://github.com/mingruimingrui/elastik-nearest-neighbors
Would you might making a branch for me to send a pull request to?

**Comment by alexklibisz** [comment]
k1 <- the number of nearest neighbors returned from the approximate KNN query.
k2 <- the number of nearest neighbors returned in the end.

Say that for your application you want ten nearest neighbors to be returned. 
Because LSH is an approximate method, it helps to first check a larger number of "approximate" neighbors and narrow down to the ten nearest neighbors.
You might set k1 = 1000 and k2 = 100.
The plugin will retrieve 1000 (k1) approximate neighbors, then compute the distance to the query vector for each of them, sort them by the distance, and return the 10 (k2) with the lowest distance.

**Comment by alexklibisz** [comment]
I will add a note in the readme that you have a build for 5.6.5 with a link to your fork.
For now I don't want to have the overhead of managing multiple branches and PRs.

**Comment by alexklibisz** [comment]
Added links to other versions here: https://github.com/alexklibisz/elastik-nearest-neighbors#elasticsearch-versions

Thanks for getting that working. Hopefully in the future I'll have time to get this working across multiple versions all in one place. Closing this one out now.
